site_name: PUPRemote Documentation
site_url: https://libs.antonsmindstorms.com/PUPRemote/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - content.code.copy
extra:
  repo_name: antonvh/PUPRemote
  repo_url: https://github.com/antonvh/PUPRemote
nav:
  - Home: index.md

plugins:
  - search
  - mkdocs-autoapi:
      autoapi_dir: src
      autoapi_ignore:
        - lpf2.py
        - pybricks_blocks_boilerplate.py
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            show_root_heading: true
            show_source: true
            docstring_style: sphinx
          


markdown_extensions:
  - admonition
  - toc:
      permalink: true
